// seasonal-react/src/pages/ProductList.tsx
import { useEffect, useState } from "react";
import Category from "data/models/category";
import categoryService from "data/services/categoryService";
import Product from "data/models/product";
import productService from "data/services/productService";
import Loader from "components/Loader";
import ProductGridItem from "components/ProductGridItem";
import ProductSearchCriteria from "data/models/product-search-criteria";
import ProductSearchForm from "components/ProductSearchForm";
import Tab from "components/Tab";
import TabGroup from "components/TabGroup";

export default function ProductList() {
    const [categories, setCategories] = useState<Category[] | null>(null);
    const [products, setProducts] = useState<Product[] | null>(null);
    const [filteredProducts, setFilteredProducts] = useState<Product[] | null>(null);
    const [searchCriteria, setSearchCriteria] = useState(new ProductSearchCriteria());

    useEffect(initData, []);
    useEffect(applyProductFilter, [categories, products, searchCriteria]);

    function initData() {
        categoryService.getAll().then(c => setCategories(c));
        productService.getAll().then(c => setProducts(c));
    }

    function applyProductFilter() {
        let filteredProducts = null;

        if (products) {
            filteredProducts = products
                .filter(p => {
                    return searchCriteria.month < 1 || p.isAvailable(searchCriteria.month)
                })
                .sort((p1, p2) => searchCriteria.ordering === "relevance" ? p1.compareByRelevance(p2, searchCriteria.month) : p1.compareByName(p2));
        }

        setFilteredProducts(filteredProducts);
    }

    function onCriteriaChange(criteria: ProductSearchCriteria) {
        setSearchCriteria(criteria);
    }

    return (
        <>
        <ProductSearchForm searchCriteria={searchCriteria} onCriteriaChange={onCriteriaChange} />
        { !categories && <Loader /> }
        { categories && 
            <TabGroup>
                {categories.map(renderCategory)}
            </TabGroup>
        }
        </>
    );
    
    function renderCategory(category: Category) {

        let categoryProducts = filteredProducts ?  filteredProducts.filter(p => p.category.categoryId === category.categoryId) : null;

        return (
            <Tab key={category.categoryId} label={category.name}>
                <div className="p-5 pt-7">
                    { !categoryProducts && <Loader /> }
                    { categoryProducts && categoryProducts.map(product => {
                        return <ProductGridItem product={product} searchCriteria={searchCriteria} key={product.productId}/>
                    })}
                </div>
            </Tab>
        );
    }
}

// seasonal-ng/src/app/products/product-list/product-list.component.ts
import { Component, OnInit } from '@angular/core';
import { BehaviorSubject, combineLatest, map, Observable } from 'rxjs';
import { Category } from '../data/models/category';
import { Product } from '../data/models/product';
import { ProductSearchCriteria } from '../data/models/product-search-criteria';
import { CategoriesService } from '../data/services/categories.service';
import { ProductsService } from '../data/services/products.service';

@Component({
  selector: 'app-product-list',
  templateUrl: './product-list.component.html',
  styleUrls: ['./product-list.component.scss']
})
export class ProductListComponent implements OnInit {

  categories!: Observable<Category[]>;
  products!: Observable<Product[]>;
  searchCriteria: ProductSearchCriteria = new ProductSearchCriteria();
  searchCriteriaSubject: BehaviorSubject<ProductSearchCriteria> = new BehaviorSubject<ProductSearchCriteria>(this.searchCriteria);

  constructor(
    private categoriesService: CategoriesService,
    private productService: ProductsService
  ) { }

  ngOnInit(): void {
    this.categories = this.categoriesService.getAll();
    this.products = this.getProducts();
  }

  getProducts() {
    let productsObservable = this.productService.getAll();

    return combineLatest({
      'products': productsObservable,
      'criteria': this.searchCriteriaSubject
    })
      .pipe(map(r => r.products
        .filter(p => {
          return r.criteria.month < 1 || p.isAvailable(r.criteria.month)
        })
        .sort((p1, p2) => r.criteria.ordering == "relevance" ? p1.compareByRelevance(p2, r.criteria.month) : p1.compareByName(p2))
      ));
  }

  onCriteriaChange() {
    this.searchCriteriaSubject.next(this.searchCriteria)
  }
}

<app-product-search-criteria [searchCriteria]="searchCriteria" (criteriaChange)="onCriteriaChange()"></app-product-search-criteria>
<mat-tab-group>
    <mat-tab label="{{category.name}}" *ngFor="let category of categories | async">
        <app-product-list-grid [category]="category" [searchCriteria]="searchCriteria" [products]="products"></app-product-list-grid>
    </mat-tab>
</mat-tab-group>
