// seasonal-react/src/components/Products/ProductAvailabilityMatrix.tsx
import Product from "data/models/product";
import SeasonalStatus from "data/models/seasonal-status";

interface ProductAvailabilityMatrixProps {
    product: Product,
    selectedMonth: number
}

export default function ProductAvailabilityMatrix({ product, selectedMonth }: ProductAvailabilityMatrixProps) {
    const months = ['January', 'February', 'March', 'April', 'May', 'June', 'July', 'August', 'September', 'October', 'November', 'December'];
    const cellContentStyle = 'w-3 h-3 text-sm mb-1';

    return (
    <div className="my-4">
        <table className="w-full border-none table-fixed">
            <tbody>
                <tr>
                    <th className="hidden">Month</th>
                    {months.map(renderHeaderCell)}
                </tr>
                <tr>
                    <th className="hidden">Availability</th>
                    {months.map(renderAvailabilityCell)}
                </tr>
            </tbody>
        </table>
    </div>
    );

    function renderHeaderCell(monthText: string, i: number) {
        let contentStyle = cellContentStyle;

        if (selectedMonth === (i + 1)) {
            contentStyle += ' font-bold';
        }

        return (
            <td title={monthText} key={monthText} className={`text-center `}>
                <span className={contentStyle}>{monthText[0]}</span>
            </td>
        );
    }

    function renderAvailabilityCell(monthText: string, i: number) {
        let seasonalStatus = product.getSeasonalStatus(i +1);
        let statusText;
        let statusDescription;
        let statusStyle;

        switch (seasonalStatus) {
            case SeasonalStatus.Available:
                statusText = 'Available';
                statusDescription = '';
                statusStyle = 'bg-yellow-200 text-black';
                break;
            case SeasonalStatus.Best:
                statusText = 'Best';
                statusDescription = '';
                statusStyle = 'bg-lime-400 text-black';
                break;
            case SeasonalStatus.NotAvailable:
                statusText = 'Not Available';
                statusDescription = '';
                statusStyle = 'bg-gray-100 text-white';
                break;
        }

        return (
            <td className={`text-center border border-black p-0 h-4 ${statusStyle}`}
                title={statusDescription}
                key={i}>
                { selectedMonth === (i + 1) &&
                    <span className={`bg-gray-800 rounded-full w-3 h-3 inline-block`}></span>
                }
                <span className="hidden">{statusText}</span>
            </td>
        );
    }
}

// seasonal-ng/src/app/components/product-availability-matrix/product-availability-matrix.component.ts
import { Component, Input, OnInit } from '@angular/core';
import { Product } from 'src/app/data/models/product';
import { SeasonalStatus } from 'src/app/data/models/seasonal-status';

@Component({
  selector: 'app-product-availability-matrix',
  templateUrl: './product-availability-matrix.component.html',
  styleUrls: ['./product-availability-matrix.component.scss']
})
export class ProductAvailabilityMatrixComponent implements OnInit {

  months: Array<string> = ['January', 'February', 'March', 'April', 'May', 'June', 'July', 'August', 'September', 'October', 'November', 'December'];
  SeasonalStatusEnum = SeasonalStatus;

  constructor() { }

  @Input() product!: Product;
  @Input() selectedMonth!: number;

  ngOnInit(): void {
  }

  getSeasonalStatusDescription(month: number) {
    switch (this.product.getSeasonalStatus(month)) {
      case SeasonalStatus.Available:
        return 'The item is usually available from a sustainable source';
      case SeasonalStatus.Best:
        return "The item is available and usually at it's best during this time.";
      case SeasonalStatus.NotAvailable:
        return 'The item is not usually available from a sustainable source.';
    }
  }
}

<div class="wrapper">
    <table>
        <tr class="row-months">
            <th>Month</th>
            <td *ngFor="let monthText of months" title="{{monthText}}"><span>{{monthText[0]}}</span></td>
        </tr>
        <tr>
            <th>Availability</th>
            <td *ngFor="let monthText of months; index as i" 
                [ngSwitch]="product.getSeasonalStatus(i + 1)" 
                class="indicator-container indicator-container-{{product.getSeasonalStatus(i + 1)}}"
                title="{{getSeasonalStatusDescription(i + 1)}}">
                <span *ngIf="selectedMonth === (i + 1)">X</span>
                <span *ngSwitchCase="SeasonalStatusEnum.Available" class="indicator">Available</span>
                <span *ngSwitchCase="SeasonalStatusEnum.Best" class="indicator">Best</span>
                <span *ngSwitchCase="SeasonalStatusEnum.NotAvailable" class="indicator">Not available</span>
            </td>
        </tr>
    </table>
</div>
